#!/bin/bash

echo Build project
./gradlew build

mkdir -p ~/opt
cd ~/opt

echo Remove former installation
rm -fr log4shell-server hello

echo Install log4shell-server
tar xf ~/src/log4shell/log4shell-server/build/distributions/log4shell-server.tar
echo Install hello-world
tar xf ~/src/log4shell/hello/build/distributions/hello.tar

mkdir -p ~/bin
cd ~/bin

rm -f log4shell-server hello
ln -s ../opt/log4shell-server/bin/log4shell-server log4shell-server
ln -s ../opt/hello/bin/hello hello

