/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package log4shell;

import com.unboundid.ldap.sdk.LDAPException;
import picocli.CommandLine;

public class ShellServer implements Runnable {
  private Config config;

  public ShellServer(Config config) {
    this.config = config;
  }

  @Override
  public void run() {
    try {
      LdapServer ldapServer = new LdapServer(config);
      System.out.println("Ready Player One");
    } catch (LDAPException e) {
      System.err.println("Failed to start");
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
    Config config = new Config();
    new CommandLine(config).parseArgs(args);
    new ShellServer(config).run();
  }
}
