/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("info.picocli:picocli:4.6.2")
    implementation("com.unboundid:unboundid-ldapsdk:6.0.3")
    implementation(platform("io.netty:netty-bom:4.1.72.Final"))
    implementation("io.netty:netty-codec-http")
    implementation(platform("com.fasterxml.jackson:jackson-bom:2.13.1"))
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    implementation(platform("software.amazon.awssdk:bom:2.17.107"))
    implementation("software.amazon.awssdk:sts")

}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass.set("log4shell.ShellServer")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
